Teacher_id = input("enter your id")
Teacher_name = input("enter your name")
Teacher_age = input ("enter your age")
Gender = input("enter your genger")
Address = input("enter your Address")
Teacher_salary = input("enter your salary")
Are_you_married = input(" are you married enter in True/False")

print(Teacher_id,type(Teacher_id))
print(Teacher_name,type(Teacher_name))
print(Teacher_age,type(Teacher_age))
print(Gender,type(Gender))
print(Address,type(Address))
print(Teacher_salary,type(Teacher_age))
print(Are_you_married,type(Are_you_married))

Teacher_id = int(input("enter your id"))
Teacher_name = input("enter your name")
Teacher_age = int(input ("enter your age"))
Gender = input("enter your genger")
Address = input("enter your Address")
Teacher_salary =float(input("enter your salary"))
Are_you_married = bool(input(" are you married enter in True/False"))

print(Teacher_id,type(Teacher_id))
print(Teacher_name,type(Teacher_name))
print(Teacher_age,type(Teacher_age))
print(Gender,type(Gender))
print(Address,type(Address))
print(Teacher_salary,type(Teacher_age))
print(Are_you_married,type(Are_you_married))
